# Generated by Django 6.0.4 on 2026-05-23 08:40

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='module',
            field=models.IntegerField(default=1, verbose_name='Номер модуля'),
        ),
    ]
