# Generated by Django 6.0.4 on 2026-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_managers_journalentry_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='grade_class',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка за классную'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='grade_homework',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка за дз'),
        ),
    ]
