# Generated by Django 6.0.5 on 2026-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_journalentry_grade_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='grade_class',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Оценка за классную'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='grade_homework',
            field=models.CharField(blank=True, default=0, null=True, verbose_name='Оценка за дз'),
        ),
    ]
